# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3464e40c14b993bb39d959adf584b62cd2fa1433539d51e23e42cae2526e66d36b82aa02ac326f574448b4e24c113a8b7079e2d0ba60305d765a480fa95ab5d

test:
  secret_key_base: bc7b7c70c49264cfbf5d3006ea287566cfadf7e5bdbd20ac5d2cd9f9a5d17a04f1296dfa2f34196d9b030f65b128586e17fed8d6d546e98ee193b1a39e710710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
